[package]
name = "update-notifier"
version = "0.1.4"
authors = ["Tarik Eshaq"]
edition = "2018"
license = "MPL-2.0"
homepage = "https://github.com/tarikeshaq/update-notifier"
repository = "https://github.com/tarikeshaq/update-notifier"
description = "Library to notify you if there are any newer versions, WORK IN PROGRESS"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crates_io_api = "0.5.1"
thiserror = "1.0"